# Generated by Django 3.1 on 2022-11-15 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(unique=True, verbose_name='URL category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255, verbose_name='Course name')),
                ('courseDescription', models.TextField(verbose_name='Course description')),
                ('courseCover', models.ImageField(upload_to='', verbose_name='Course cover')),
                ('postDate', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(unique=True, verbose_name='URL course')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatformApp.category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themeName', models.CharField(max_length=255, verbose_name='Theme name')),
                ('themeDescription', models.TextField(verbose_name='Theme description')),
                ('videoUrl', models.CharField(max_length=500, verbose_name='Video URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduPlatformApp.course', verbose_name='Course')),
            ],
            options={
                'verbose_name_plural': 'Themes',
            },
        ),
    ]
